[package]
name = "normal-rust-types"
version = "0.1.4"
edition = "2021"
description="A common Rust types library for the entire Normal Finance Ecosystem"
license = "Apache-2.0"
authors = ["Jay Malve <jaymalveus@gmail.com>", "Joshua Blew <joshua@normalfinance.io>"]

[dependencies]
soroban-sdk = "22.0.1"
soroban-fixed-point-math = "1.3.0"


[lib]
path = "src/lib.rs"
